version : "3.4"
services : 
  api-service :
    build : 
      context: .
    image : worker1:5000/kmitl-weather-api-service
    networks: 
      - default
    restart: always
    ports : 
      - 5006:5006
  
networks:
  default:
    external:
#      name: apicekmitl_network
      name: ticketing_default